fix: error out of resolve-site if /emergence/sites tree does not exist

diff --git a/bin/resolve-site b/bin/resolve-site
--- a/bin/resolve-site
+++ b/bin/resolve-site
@@ -1,13 +1,14 @@
 #!/bin/bash
 
 die () {
-    echo >&2 "$@"
+    echo >&2 "emergence-resolve-site: $@"
     exit 1
 }
 
 
 # check usage
 [ -n "$1" ] || die "Usage: emergence-resolve-site <hostname>"
+[ -d "/emergence/sites" ] || die "/emergence/sites not found"
 
 
 # determine location of this script
